[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn src.backend.api:app --host 0.0.0.0 --port $PORT"
<<<<<<< HEAD
restartPolicyType = "ON_FAILURE"
=======
restartPolicyType = "ON_FAILURE"
>>>>>>> b39f1a56e5b47ac60b5ac0965856ed7134916991
